// Etiquetas estáticas en español — reemplaza el antiguo sistema i18n eliminado
// Se usa únicamente para lookups dinámicos (variable como key)
const LABELS: Record<string, string> = {
  // ===== modules =====
  'modules.dashboard': 'Tablero de Control',
  'modules.logical-framework': 'Marco Lógico',
  'modules.A': 'A. Datos del Proyecto',
  'modules.B': 'B. Construcción y Montaje',
  'modules.C': 'C. Gastos de Capital',
  'modules.D': 'D. Subcontrataciones',
  'modules.E': 'E. Recursos Humanos',
  'modules.F': 'F. Materias Primas',
  'modules.G': 'G. Salarios',
  'modules.H': 'H. Ventas',
  'modules.I': 'I. Gastos de Distribución y Ventas',
  'modules.J': 'J. Gastos Generales y de Administración',
  'modules.K': 'K. Mantenimiento',
  'modules.L': 'L. Otros Gastos',
  'modules.M': 'M. Financiamiento',
  'modules.N': 'N. Parámetros',
  'modules.spare-parts': 'Piezas y Herramientas',
  'modules.other-resources': 'Otros Recursos y Gastos',
  'modules.intangible-assets': 'Activos Intangibles',
  'modules.direct-costs': 'Costos Directos',
  'modules.investment-budget': 'Presupuesto de Inversión',
  'modules.investment-schedule': 'Cronograma de Inversión',
  'modules.depreciation': 'Depreciación',
  'modules.costs-financial': 'Costos Financieros',
  'modules.working-capital': 'Capital de Trabajo',
  'modules.cash-flow-planning': 'Planificación Financiera',
  'modules.cash-flow-investment': 'Flujo de Caja — Inversión y Capital Social',
  'modules.currency-effect': 'Efecto sobre Divisas',
  'modules.utility-distribution': 'Distribución de Utilidades',
  'modules.indicators': 'Indicadores',
  'modules.sensitivity': 'Sensibilidad',
  'modules.scenarios': 'Escenarios',
  'modules.balance-sheet': 'Balance General',
  'modules.income-statement': 'Estado de Rendimiento',
  'modules.other-taxes': 'Otros Impuestos',
  'modules.pdf-report': 'Exportar',

  // ===== sidebar sections =====
  'sidebar.panel': 'Panel',
  'sidebar.logicalFramework': 'Marco Lógico',
  'sidebar.dataAndParameters': 'Datos y Parámetros',
  'sidebar.initialInvestment': 'Inversión Inicial',
  'sidebar.operations': 'Operaciones',
  'sidebar.results': 'Resultados',

  // ===== sidebar items =====
  'sidebar.mainDashboard': 'Tablero de Control',
  'sidebar.projectData': 'A. Datos del Proyecto',
  'sidebar.financialParameters': 'N. Parámetros Financieros',
  'sidebar.construction': 'B. Construcción y Montaje',
  'sidebar.capitalExpenditures': 'C. Gastos de Capital',
  'sidebar.subcontracting': 'D. Subcontrataciones',
  'sidebar.humanResources': 'E. Recursos Humanos',
  'sidebar.sparePartsAndTools': 'Piezas y Herramientas',
  'sidebar.otherResources': 'Otros Recursos',
  'sidebar.intangibleAssets': 'Activos Intangibles',
  'sidebar.financing': 'M. Financiamiento',
  'sidebar.purchasesMP': 'F. Materias Primas',
  'sidebar.salaries': 'G. Salarios',
  'sidebar.sales': 'H. Ingresos',
  'sidebar.directCosts': 'Costos Directos',
  'sidebar.commercialExpenses': 'I. Gastos de Distribución y Ventas',
  'sidebar.adminExpenses': 'J. Gastos Generales y de Administración',
  'sidebar.maintenance': 'K. Mantenimiento',
  'sidebar.indirectExpenses': 'L. Otros Gastos',
  'sidebar.investmentBudget': 'Presupuesto de Inversión',
  'sidebar.investmentSchedule': 'Cronograma de Inversión',
  'sidebar.depreciation': 'Depreciación',
  'sidebar.financialCosts': 'Costos Financieros',
  'sidebar.erf': 'Estados Financieros',
  'sidebar.workingCapital': 'Capital de Trabajo',
  'sidebar.planningCashFlow': 'Planificación Financiera',
  'sidebar.investmentCashFlow': 'Flujo de Caja — Inversión y Capital Social',
  'sidebar.balanceSheet': 'Balance General',
  'sidebar.currencyEffect': 'Efecto sobre Divisas',
  'sidebar.utilityDistribution': 'Distribución de Utilidades',
  'sidebar.indicators': 'Indicadores',
  'sidebar.sensitivity': 'Sensibilidad',
  'sidebar.scenarios': 'Escenarios',
  'sidebar.otherTaxes': 'Otros Impuestos',
  'sidebar.exportFormats': 'Exportar',

  // ===== indicators =====
  'indicators.van': 'VAN',
  'indicators.irr': 'TIR',
  'indicators.pra': 'PR A',
  'indicators.praPos': 'PR A Positivo',
  'indicators.rvani': 'RVAN/i',
  'indicators.lcoe': 'LCOE',
  'indicators.roi': 'ROI',
  'indicators.npv': 'VPN',
  'indicators.pbpa': 'PBPA',
  'indicators.bcRatio': 'R B/C',

  // ===== common =====
  'common.concept': 'Concepto',
  'common.direct': 'Directos',
  'common.indirect': 'Indirectos',
  'common.annualView': 'Vista Anual',
  'common.monthWord': 'meses',

  // ===== parameters =====
  'parameters.exchangeRates': 'Tipo de Cambio',
  'parameters.financialRates': 'Tasas Financieras',
  'parameters.contributions': 'Contribuciones',

  // ===== export =====
  'export.exportFullReport': 'Exportar Informe Completo',
  'export.word': 'Word',
  'export.excel': 'Excel',
  'export.generating': 'Generando...',
  'export.exportWord': 'Exportar Word',
  'export.exportExcel': 'Exportar Excel',

  // ===== cost module / ops =====
  'costModule.fields.name': 'Nombre',
  'costModule.fields.description': 'Descripción',
  'costModule.fields.quantity': 'Cantidad',
  'costModule.fields.unitPriceCUP': 'Precio Unitario CUP',
  'costModule.fields.unitPriceMLC': 'Precio Unitario MLC',
  'costModule.fields.totalCUP': 'Total CUP',
  'costModule.fields.totalMLC': 'Total MLC',
  'costModule.fields.category': 'Categoría',
  'costModule.fields.months': 'Meses',

  // ===== currency effect =====
  'currencyEffect.exchangeRateEffect': 'Efecto Tipo de Cambio',
  'currencyEffect.totalEffect': 'Efecto Total',

  // ===== financial costs =====
  'financialCosts.amortization': 'Amortización',
  'financialCosts.interest': 'Intereses',

  // ===== parameters form =====
  'parameters.taxes': 'Impuestos y Tasas',
  'parameters.taxesDescription': 'Configuración de tasas impositivas y contribuciones aplicables',
  'parameters.incomeTax': 'Impuesto sobre Utilidades (%)',
  'parameters.salesTax': 'Impuesto sobre Ventas (ISV %)',
  'parameters.specialSocialSecurity': 'CSS Especial Patronal (%)',
  'parameters.workforceTax': 'Impuesto sobre la Fuerza de Trabajo (%)',
  'parameters.personalIncomeTaxExemptMin': 'IIP Mínimo Exento (CUP)',
  'parameters.personalIncomeTax': 'Impuesto sobre Ingresos Personales (%)',
  'parameters.workerSocialSecurity': 'CSS Trabajadores (%)',
  'parameters.territorialTax': 'Contribución al Desarrollo Local (%)',
  'parameters.honorariosAdmin': 'Honorarios de Administración (%)',
  'parameters.discount': 'Descuento y Tasa de Referencia',
  'parameters.discountDescription': 'Tasas para evaluación financiera del proyecto',
  'parameters.cupDiscountRate': 'Tasa de Descuento CUP (%)',
  'parameters.mlcDiscountRate': 'Tasa de Descuento MLC (%)',
  'parameters.minimumAcceptableRate': 'Tasa Mínima Aceptable (%)',
  'parameters.inflationRate': 'Tasa de Inflación (%)',
  'parameters.reserves': 'Reservas y Retenciones',
  'parameters.reservesDescription': 'Porcentajes de reservas y utilidades retenidas',
  'parameters.contingencyReserveInvestment': 'Reserva de Contingencia Inversión (%)',
  'parameters.operationsContingency': 'Reserva de Contingencia Operaciones (%)',
  'parameters.retainedEarnings': 'Utilidades Retenidas (%)',
  'parameters.distribution': 'Distribución de Utilidades',
  'parameters.distributionDescription': 'Distribución de utilidades según normativa vigente',
  'parameters.dividendCAM': 'Dividendo CAM (%)',
  'parameters.projectAccount': 'Cuenta de Proyecto (%)',
  'parameters.arie': 'Aporte Rendimiento Inversión Estatal — ARIE (%)',
  'parameters.reservasEstimulacion': 'Reservas de Estimulación (%)',
  'parameters.beneficioReinvertir': 'Utilidades a Reinvertir (%)',
  'parameters.canonRoyalties': 'Canon y Royalties (% sobre Ventas Netas)',
  'parameters.arrendamiento': 'Gastos de Arrendamiento (CUP/mes)',
  'parameters.otrosGastosVariables': 'Otros Gastos Variables (% Ventas Netas)',
  'parameters.otrasReservasVoluntarias': 'Otras Reservas Voluntarias (% Utilidad Neta)',
  'parameters.pagoUtilidadesRetenidas': 'Pago Utilidades Retenidas (CUP/mes)',
  'parameters.dividendoEstatal': 'Dividendo Empresa Estatal (% Util. Distribuir)',
  'parameters.dividendoSocioCubano': 'Dividendo Socio Cubano (% Util. Distribuir)',
  'parameters.dividendoSocioExtranjero': 'Dividendo Socio Extranjero (% Util. Distribuir)',
  'parameters.financial': 'Parámetros Financieros',
  'parameters.financialDescription': 'Comisiones bancarias y normas laborales',
  'parameters.bankCommission': 'Comisión Bancaria (%)',
  'parameters.vacationNorm': 'Norma de Vacaciones (%)',
  'parameters.socialSecurity': 'Seguridad Social',
  'parameters.workingCapital': 'Capital de Trabajo',
  'parameters.workingCapitalDescription': 'Parámetros para el cálculo del capital de trabajo',
  'parameters.workingDaysPerYear': 'Días Laborables por Año',
  'parameters.workingDaysPerMonth': 'Días Laborables por Mes',
  'parameters.cashCoverageDays': 'Cobertura de Efectivo (días)',
  'parameters.receivableCoverageDays': 'Cobertura de Cuentas por Cobrar (días)',
  'parameters.inventoryRotationDays': 'Rotación de Inventario (días)',
  'parameters.supplierPaymentDays': 'Pago a Proveedores (días)',
  'parameters.wipDays': 'Productos en Proceso (días)',
  'parameters.finishedGoodsCoverageDays': 'Productos Terminados (días)',
  'parameters.sparePartsCoverageDays': 'Repuestos (días)',
  'parameters.mercanciasVentaCoverageDays': 'Días Mercancías Venta',
  'parameters.buildings': 'Edificaciones',
  'parameters.infrastructure': 'Infraestructura',
  'parameters.machineryEquipment': 'Maquinaria y Equipo',
  'parameters.transportEquipment': 'Equipo de Transporte',
  'parameters.computingEquipment': 'Equipo de Cómputo',
  'parameters.furnitureFixtures': 'Mobiliario y Enseres',
  'parameters.tools': 'Herramientas',
  'parameters.otherAssets': 'Otros Activos',
  'parameters.softwareLicenses': 'Licencias de Software',
  'parameters.patents': 'Patentes',
  'parameters.trademarks': 'Marcas Registradas',
  'parameters.licensesConcessions': 'Licencias y Concesiones',
  'parameters.organizationExpenses': 'Gastos de Organización',
  'parameters.staffTraining': 'Capacitación del Personal',
  'parameters.knowhowTransfer': 'Transferencia de Know-How',
  'parameters.qrLinear': 'Línea Recta',

  // ===== utility distribution =====
  'utilityDistribution.contributions': 'Contribuciones',

  // ===== working capital =====
  'workingCapital.rotationDays': 'Días de Rotación',

  // ===== flujo de caja — planificación financiera =====
  // Secciones de actividad (Resolución 1/2022)
  'cashFlowPlanning.sectionInversiones': 'I. FLUJO DE CAJA EN INVERSIONES',
  'cashFlowPlanning.sectionFinanciamiento': 'II. FLUJO DE CAJA POR FINANCIAMIENTO',
  'cashFlowPlanning.sectionOperaciones': 'III. FLUJO DE CAJA EN OPERACIONES',
  'cashFlowPlanning.saldosConsolidados': 'SALDOS CONSOLIDADOS',
  // Conceptos comunes
  'cashFlowPlanning.entradasTitle': 'ENTRADAS',
  'cashFlowPlanning.salidasTitle': 'SALIDAS',
  'cashFlowPlanning.saldosTitle': 'SALDOS',
  // I. Inversiones
  'cashFlowPlanning.valorRemanente': 'Valor Remanente de Activos',
  'cashFlowPlanning.inversionFija': 'Inversión Fija',
  'cashFlowPlanning.activosIntangibles': '( incl. Activos Fijos Intangibles )',
  'cashFlowPlanning.gastosPrevios': 'Gastos Previos a la Operación',
  'cashFlowPlanning.capitalFijo': 'Capital Fijo',
  'cashFlowPlanning.capitalTrabajoInicial': 'Capital de Trabajo Inicial',
  'cashFlowPlanning.variacionCT': 'Variación Capital de Trabajo',
  'cashFlowPlanning.interesesCapitalizados': 'Intereses Capitalizados (info)',
  'cashFlowPlanning.saldoInversiones': 'Saldo FC en Inversiones',
  // II. Financiamiento
  'cashFlowPlanning.capitalSocial': 'Capital Social',
  'cashFlowPlanning.financiamiento': 'Financiamiento',
  'cashFlowPlanning.recursosFinancieros': 'Recursos Financieros',
  'cashFlowPlanning.interesesDeuda': 'Intereses de la Deuda',
  'cashFlowPlanning.reembolsoPrincipal': 'Reembolso del Principal',
  'cashFlowPlanning.servicioDeuda': 'Servicio de la Deuda',
  'cashFlowPlanning.saldoFinanciamiento': 'Saldo FC por Financiamiento',
  // III. Operaciones
  'cashFlowPlanning.ventasNetas': 'Ingresos por Ventas Netas',
  'cashFlowPlanning.otrosIngresos': 'Otros Ingresos',
  'cashFlowPlanning.capitalTrabajoPrecedente': 'Capital de Trabajo del Año Precedente',
  'cashFlowPlanning.totalEntradasOp': 'Total Entradas Operaciones',
  'cashFlowPlanning.costosVariables': 'Costos Variables',
  'cashFlowPlanning.costosFijos': 'Costos Fijos',
  'cashFlowPlanning.costosOperacion': 'Costos de Operación',
  'cashFlowPlanning.honorariosAdmin': 'Honorarios de Administración',
  'cashFlowPlanning.gastosFinancieros': 'Gastos Financieros (excl. intereses)',
  'cashFlowPlanning.impuestoUtilidades': 'Impuesto sobre Utilidades',
  'cashFlowPlanning.otrosImpuestos': 'Otros Impuestos, Tasas y Contribuciones',
  'cashFlowPlanning.reservasEstimulacion': 'Reservas para el Fondo de Estimulación',
  'cashFlowPlanning.totalSalidasOp': 'Total Salidas Operaciones',
  'cashFlowPlanning.saldoOperaciones': 'Saldo FC en Operaciones',
  // Consolidado
  'cashFlowPlanning.saldoAnual': 'Saldo Anual',
  'cashFlowPlanning.saldoAcumulado': 'Saldo Acumulado',
  'cashFlowPlanning.totalEntradas': 'Total Entradas',
  'cashFlowPlanning.totalSalidas': 'Total Salidas',
  // Viabilidad por Flujos Acumulados
  'cashFlowPlanning.viabilityTitle': 'Análisis de Viabilidad por Flujos Acumulados',
  'cashFlowPlanning.yearsNegativeFlow': 'Años con Flujo Negativo',
  'cashFlowPlanning.worstAccumulated': 'Peor Saldo Acumulado',
  'cashFlowPlanning.recoveryYear': 'Año de Recuperación',
  'cashFlowPlanning.finalAccumulated': 'Saldo Acumulado Final',
  'cashFlowPlanning.viable': 'Viable',
  'cashFlowPlanning.notViable': 'No Viable',
  'cashFlowPlanning.risky': 'Riesgoso',
  'cashFlowPlanning.viabilityDescription': 'Evalúa si el flujo de caja acumulado se mantiene positivo o recupera durante la vida útil del proyecto.',
  'cashFlowPlanning.noRecovery': 'Sin recuperación',
  'cashFlowPlanning.neverNegative': 'Nunca negativo',
  // KPI cards
  'cashFlowPlanning.kpiTotalEntradas': 'Total Entradas',
  'cashFlowPlanning.kpiTotalSalidas': 'Total Salidas',
  'cashFlowPlanning.kpiInversiones': 'Saldo Inversiones',
  'cashFlowPlanning.kpiFinanciamiento': 'Saldo Financiamiento',
  'cashFlowPlanning.kpiOperaciones': 'Saldo Operaciones',
  'cashFlowPlanning.projectDuration': 'Duración del Proyecto',

  // ===== flujo de caja — inversión =====
  'cashFlowInvestment.entradas': 'ENTRADAS',
  'cashFlowInvestment.salidas': 'SALIDAS',
  'cashFlowInvestment.ventasNetas': 'Ventas Netas',
  'cashFlowInvestment.valorDesecho': 'Valor de Desecho',
  'cashFlowInvestment.valorDesechoTitle': 'VALOR DE DESECHO Y ACTIVOS',
  'cashFlowInvestment.totalEntradas': 'Total Entradas',
  'cashFlowInvestment.inversionTotal': 'Inversión Total',
  'cashFlowInvestment.capitalFijo': 'Capital Fijo',
  'cashFlowInvestment.activosIntangibles': '( incl. Activos Fijos Intangibles )',
  'cashFlowInvestment.gastosPrevios': 'Gastos Previos a la Operación',
  'cashFlowInvestment.capitalTrabajoInicial': 'Capital de Trabajo Inicial',
  'cashFlowInvestment.variacionCapitalTrabajo': 'Variación Capital de Trabajo',
  'cashFlowInvestment.costosOperacion': 'Costos de Operación',
  'cashFlowInvestment.contribucionSeguridadSocial': 'Contribución Seguridad Social',
  'cashFlowInvestment.honorariosAdmin': 'Honorarios de Administración',
  'cashFlowInvestment.reservasEstimulacion': 'Reservas para el Fondo de Estimulación',
  'cashFlowInvestment.impuestoUtilidades': 'Impuesto sobre Utilidades',
  'cashFlowInvestment.otrosImpuestosTasas': 'Otros Impuestos, Tasas y Contribuciones',
  'cashFlowInvestment.totalSalidas': 'Total Salidas',
  'cashFlowInvestment.valorActualActivos': 'Valor Actual de los Activos Existentes',
  'cashFlowInvestment.valorActualCapitalFijo': 'Capital Fijo',
  'cashFlowInvestment.valorActualIntangibles': 'Activos Intangibles',
  'cashFlowInvestment.valorActualGastosPrevios': 'Gastos Previos (no amortizados)',
  'cashFlowInvestment.saldoAnual': 'Saldo Anual',
  'cashFlowInvestment.saldoAcumulado': 'Saldo Acumulado',
  'cashFlowInvestment.prestamosRecibidos': 'Préstamos Recibidos',
  'cashFlowInvestment.capitalSocialPropio': 'Capital Social Propio',
  'cashFlowInvestment.capitalSocial': 'Capital Social',
  'cashFlowInvestment.inversionTotalNegativa': 'Inversión Total',
  'cashFlowInvestment.serviciosDeuda': 'Servicios de la Deuda',
  'cashFlowInvestment.interesesDeuda': 'Intereses de la Deuda',
  'cashFlowInvestment.reembolsoPrincipal': 'Reembolso del Principal',
  'cashFlowInvestment.impuestos': 'Impuestos (ISU + CSS + ITF)',
  'cashFlowInvestment.gastosBancarios': 'Gastos Bancarios',
  'cashFlowInvestment.tasaActualizacion': 'Tasa de Actualización',
  'cashFlowInvestment.valorRemanenteUltimoAnio': 'Valor Remanente Último Año',
  'cashFlowInvestment.flujoCajaActualizado': 'Flujo de Caja Actualizado',
  'cashFlowInvestment.flujoCajaActualizadoAcumulado': 'Flujo de Caja Actualizado Acumulado',

  // ===== operations wrapper — salary labels =====
  'opsWrapper.salaryLabels.F': 'Personal de Compras / MP',
  'opsWrapper.salaryLabels.I': 'Personal de Distribución y Ventas',
  'opsWrapper.salaryLabels.J': 'Personal de Gral. y Administración',
  'opsWrapper.salaryLabels.K': 'Personal de Mantenimiento',
  'opsWrapper.salaryLabels.L': 'Personal de Otros Gastos',

  // ===== direct costs module =====
  'directCostsModule.salaryTitle': 'Salarios de Costos Directos',
  'directCostsModule.salaryDescription': 'Personal asignado a los costos directos de producción',
};

// Se puede extender dinámicamente si se necesita
export function L(key: string): string {
  return LABELS[key] ?? key;
}
