/**
 * BARAPRO v11 — postbuild.js
 *
 * Cross-platform post-build script that replaces Unix-only `cp` commands
 * in the build pipeline. Handles:
 *   1. Flatten nested standalone directory (Next.js 16 nests under project name)
 *   2. Copying .next/static → .next/standalone/.next/static
 *   3. Copying public/ → .next/standalone/public/
 *   4. Safety net: ensure pages-manifest.json and error pages exist
 *
 * This is called automatically by `npm run build` via package.json.
 * It also runs as part of install.js → copyStandaloneFiles().
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const STANDALONE_DIR = path.join(ROOT_DIR, '.next', 'standalone');

/**
 * Copy a directory recursively (cross-platform, no Unix cp dependency).
 */
function copyDirSync(src, dest) {
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Flatten nested standalone directory.
 * Next.js 16 may nest standalone output under the project directory name.
 * E.g., .next/standalone/my-project/server.js → .next/standalone/server.js
 */
function flattenStandaloneDir() {
  if (!fs.existsSync(STANDALONE_DIR)) return;

  // Already flat?
  if (fs.existsSync(path.join(STANDALONE_DIR, 'server.js'))) return;

  // Find the nested directory
  const entries = fs.readdirSync(STANDALONE_DIR, { withFileTypes: true });
  const nestedDir = entries.find(e =>
    e.isDirectory() &&
    fs.existsSync(path.join(STANDALONE_DIR, e.name, 'server.js'))
  );

  if (!nestedDir) return;

  const nestedPath = path.join(STANDALONE_DIR, nestedDir.name);
  console.log('[postbuild] Detected nested standalone in: ' + nestedDir.name);
  console.log('[postbuild] Flattening structure...');

  // Move all items from nested dir up to standalone root
  const items = fs.readdirSync(nestedPath, { withFileTypes: true });
  for (const item of items) {
    const src = path.join(nestedPath, item.name);
    const dest = path.join(STANDALONE_DIR, item.name);

    // If destination already exists, merge directories
    if (fs.existsSync(dest)) {
      if (item.isDirectory()) {
        copyDirSync(src, dest);
      }
      // Skip if file already exists at destination
    } else {
      // Move the item
      fs.renameSync(src, dest);
    }
  }

  // Remove the now-empty nested directory
  try {
    fs.rmSync(nestedPath, { recursive: true, force: true });
  } catch {
    // Ignore cleanup errors
  }

  console.log('[postbuild] Standalone structure flattened.');
}

function main() {
  // Check standalone directory exists
  if (!fs.existsSync(STANDALONE_DIR)) {
    console.warn('[postbuild] .next/standalone not found — skipping post-build steps.');
    console.warn('[postbuild] This is normal during development (next dev).');
    return;
  }

  // 0. Flatten nested standalone directory FIRST
  flattenStandaloneDir();

  // Verify server.js exists after flatten
  if (!fs.existsSync(path.join(STANDALONE_DIR, 'server.js'))) {
    console.warn('[postbuild] server.js not found in standalone — build may be incomplete.');
    return;
  }

  // 1. Copy .next/static → .next/standalone/.next/static
  const staticSrc = path.join(ROOT_DIR, '.next', 'static');
  const staticDest = path.join(STANDALONE_DIR, '.next', 'static');
  if (fs.existsSync(staticSrc)) {
    copyDirSync(staticSrc, staticDest);
    console.log('[postbuild] Copied .next/static → standalone');
  } else {
    console.warn('[postbuild] .next/static not found — skipping static copy.');
  }

  // 2. Copy public/ → .next/standalone/public/
  const publicSrc = path.join(ROOT_DIR, 'public');
  const publicDest = path.join(STANDALONE_DIR, 'public');
  if (fs.existsSync(publicSrc)) {
    copyDirSync(publicSrc, publicDest);
    console.log('[postbuild] Copied public/ → standalone');
  } else {
    console.warn('[postbuild] public/ not found — skipping public copy.');
  }

  // 3. Safety net: ensure pages-manifest.json exists
  //    Next.js 16 standalone server CRASHES with ENOENT if this file is missing.
  //    It's normally generated by `next build`, but can be lost during
  //    Windows xcopy/flatten operations or antivirus interference.
  const serverDir = path.join(STANDALONE_DIR, '.next', 'server');
  if (fs.existsSync(serverDir)) {
    const manifestPath = path.join(serverDir, 'pages-manifest.json');
    if (!fs.existsSync(manifestPath)) {
      fs.writeFileSync(manifestPath, JSON.stringify({
        "/404": "pages/404.html",
        "/500": "pages/500.html"
      }, null, 2));
      console.warn('[postbuild] Created missing pages-manifest.json');
    }

    // Ensure error pages directory exists
    const pagesDir = path.join(serverDir, 'pages');
    if (!fs.existsSync(pagesDir)) {
      fs.mkdirSync(pagesDir, { recursive: true });
    }

    // Ensure 404.html exists
    const page404 = path.join(pagesDir, '404.html');
    if (!fs.existsSync(page404)) {
      fs.writeFileSync(page404, '<!DOCTYPE html><html><head><meta charset="utf-8"><title>404</title></head><body><h1>404 - Page Not Found</h1></body></html>');
      console.warn('[postbuild] Created missing 404.html');
    }

    // Ensure 500.html exists
    const page500 = path.join(pagesDir, '500.html');
    if (!fs.existsSync(page500)) {
      fs.writeFileSync(page500, '<!DOCTYPE html><html><head><meta charset="utf-8"><title>500</title></head><body><h1>500 - Internal Server Error</h1></body></html>');
      console.warn('[postbuild] Created missing 500.html');
    }
  }

  console.log('[postbuild] Post-build steps completed.');
}

main();
